stages:
  - build

build-job:
  image: maven:3.9.9-eclipse-temurin-17-focal
  stage: build
  tags:
    - comp2120
  artifacts:
    when: always
    paths:
      - target/*.jar
  script:
    - mvn clean build
