image: maven:3.8-openjdk-17

stages:
  - build
  - test

build-job:
  stage: build
  tags:
    - comp2120
    - comp2300
    - comp2100
  artifacts:
    when: always
    paths:
      - target/*.jar
  script:
    - mvn clean package

test-job:
  stage: test
  tags:
    - comp2120
    - comp2300
    - comp2100
  script:
    - mvn test
